/*
 * MySwing2.java
 *
 * Created on __DATE__, __TIME__
 */

package com.hz.ui;

/**
 *
 * @author  __USER__
 */
public class MyPhoto extends javax.swing.JFrame {

	/** Creates new form MySwing2 */
	public MyPhoto() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTree1 = new javax.swing.JTree();
		jScrollPane2 = new javax.swing.JScrollPane();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jComboBox1 = new javax.swing.JComboBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jScrollPane1.setViewportView(jTree1);

		jLabel1.setIcon(new javax.swing.ImageIcon(
				"F:\\mygit\\github\\threed-client\\threed-client\\threed-client\\image\\tupian1.png")); // NOI18N
		jLabel1.setText("jLabel1");

		jLabel2.setIcon(new javax.swing.ImageIcon(
				"F:\\mygit\\github\\threed-client\\threed-client\\threed-client\\image\\tupian1.png")); // NOI18N
		jLabel2.setText("jLabel1");

		jLabel3.setIcon(new javax.swing.ImageIcon(
				"F:\\mygit\\github\\threed-client\\threed-client\\threed-client\\image\\tupian1.png")); // NOI18N
		jLabel3.setText("jLabel1");

		jLabel4.setIcon(new javax.swing.ImageIcon(
				"F:\\mygit\\github\\threed-client\\threed-client\\threed-client\\image\\tupian1.png")); // NOI18N
		jLabel4.setText("jLabel1");

		jLabel5.setIcon(new javax.swing.ImageIcon(
				"F:\\mygit\\github\\threed-client\\threed-client\\threed-client\\image\\tupian1.png")); // NOI18N
		jLabel5.setText("jLabel1");

		jLabel6.setIcon(new javax.swing.ImageIcon(
				"F:\\mygit\\github\\threed-client\\threed-client\\threed-client\\image\\tupian1.png")); // NOI18N
		jLabel6.setText("jLabel1");

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel1Layout
								.createSequentialGroup()
								.addContainerGap()
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(jLabel1,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														243,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.UNRELATED)
												.add(jLabel2,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														231,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.RELATED)
												.add(jLabel3,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														231,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.add(jPanel1Layout
												.createSequentialGroup()
												.add(jLabel4,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														231,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(24, 24, 24)
												.add(jLabel5,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														231,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(
														org.jdesktop.layout.LayoutStyle.UNRELATED)
												.add(jLabel6,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														231,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(221, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel1Layout
								.createSequentialGroup()
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel2,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												227,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												227,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel3,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												227,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jPanel1Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jLabel4,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												227,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel6,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												227,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jLabel5,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												227,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(44, Short.MAX_VALUE)));

		jScrollPane2.setViewportView(jPanel1);

		jTextField1.setText("");

		jButton1.setText("全部");

		jButton2.setText("免费");

		jButton3.setText("付费");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.add(jScrollPane1,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.LEADING)
								.add(layout
										.createSequentialGroup()
										.add(jScrollPane2,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												734, Short.MAX_VALUE)
										.addContainerGap())
								.add(org.jdesktop.layout.GroupLayout.TRAILING,
										layout.createSequentialGroup()
												.add(jTextField1,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														311, Short.MAX_VALUE)
												.add(18, 18, 18)
												.add(jButton1)
												.add(27, 27, 27)
												.add(jButton2)
												.add(18, 18, 18)
												.add(jButton3)
												.add(39, 39, 39)
												.add(jComboBox1,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(25, 25, 25)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(jScrollPane1,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 550,
						Short.MAX_VALUE)
				.add(layout
						.createSequentialGroup()
						.addContainerGap()
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.LEADING)
								.add(layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.BASELINE)
										.add(jComboBox1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(jButton3).add(jButton2)
										.add(jButton1))
								.add(jTextField1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jScrollPane2,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								485, Short.MAX_VALUE).add(18, 18, 18)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MySwing2().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTree jTree1;
	// End of variables declaration//GEN-END:variables

}